const {chromium}=require(process.env.AVERY_PLAYWRIGHT||'playwright');const fs=require('fs'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
(async()=>{const b=await chromium.launch({channel:process.env.AVERY_BROWSER==='chromium'?undefined:(process.env.AVERY_BROWSER||'msedge'),headless:true}),c=await b.newContext({viewport:{width:390,height:844}});await c.route('http://avery.test/**',r=>{const u=r.request().url();return r.fulfill(u.includes('/api/')?{status:404,body:''}:u.endsWith('initial-plan.json')?{contentType:'application/json',body:fs.readFileSync(path.join(root,'initial-plan.json'),'utf8')}:{contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')})});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://avery.test/');await p.waitForFunction(()=>appReady);assert.ok((await p.locator('#ovTiles').innerText()).includes('CONVERSATIONS AGREED')); 
await p.locator('#planSearch').fill('stroller');assert.ok(await p.locator('#searchResults button').count()>0);await p.locator('#searchResults button').filter({hasText:/^Stroller/}).click();assert.equal(await p.locator('#p-buy').getAttribute('class'),'panel on');
await p.locator('.buy').first().getByRole('button',{name:'Compare tiers'}).click();await p.locator('.buy [data-tier="premium"]').first().focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('data-tier')),'premium');
await p.locator('#undoPlan').click();assert.ok(await p.locator('#undoPlan').isDisabled());
await p.locator('[data-tab="money"]').click();const before=await p.evaluate(()=>JSON.stringify(S));await p.locator('#scenarios').click();await p.locator('dialog [data-budget="help"]').selectOption('none');assert.ok((await p.locator('#budgetDelta').innerText()).includes('compared'));await p.locator('dialog').getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await p.evaluate(()=>JSON.stringify(S)),before);
await p.locator('#cashflow').click();const sums=await p.evaluate(()=>({shown:document.querySelector('#flowPeak').textContent,net:money(model().netCash)}));assert.ok(sums.shown.includes('Year-one net: '+sums.net));await p.locator('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
await p.locator('[data-tab="discuss"]').click();await p.locator('.task[data-id="q20"] [data-budget-edit]').click();await p.locator('dialog [data-budget="help"]').selectOption('family');await p.locator('dialog').getByRole('button',{name:'Apply these choices'}).click();assert.equal(await p.evaluate(()=>cfg('help')),'family');
await p.locator('#dsFilters [data-owner="Him"]').click();assert.equal(await p.locator('.task:not([data-owner="Him"])').count(),0);await p.locator('#dsFilters [data-owner="All"]').click();
await p.locator('#planSettings summary').click();await p.locator('#planStage').selectOption('trying');assert.equal(await p.evaluate(()=>todayWk()),-12);await p.locator('#planStage').selectOption('born');await p.locator('#birthDate').fill('2026-09-01');await p.locator('#birthDate').dispatchEvent('change');assert.equal(await p.evaluate(()=>cfg('stage')),'born');
await p.locator('[data-tab="overview"]').click();await p.locator('[data-tab="money"]').click();await p.goBack();assert.equal(await p.locator('#p-overview').getAttribute('class'),'panel on');
const invalid=await p.evaluate(()=>{let rejected=0;for(const x of [{tasks:[]},{settings:{hosp:-1}},{tasks:{q20:{notes:[]}}}])try{validatePlan(x)}catch{rejected++}return rejected});assert.equal(invalid,3);
await p.locator('#shareBtn').click();// The isolated test attaches a file directly; no native picker or real data is used.
await p.locator('input[data-restorefile]').setInputFiles({name:'import.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({app:'Avery Plan',settings:{cdaDeposit:2500},tasks:{},buys:{},checks:{}}))});await p.locator('dialog').getByRole('button',{name:'Merge answers'}).click();assert.equal(await p.evaluate(()=>cfg('cdaDeposit')),2500);
await p.setViewportSize({width:320,height:844});assert.deepEqual(errors,[]);console.log('PASS seeded answers, search, keyboard tier choice, undo, scenario isolation, cashflow reconciliation, explicit budget choice, owner filters, planning stage, Back navigation, import validation and merge');await b.close();})();


